version: '3'
services:
  c9:
    container_name: c9u01
    build: 
      context: './c9'
      dockerfile: 'minimal/Dockerfile'
    ports:
      - 80:80
      - 9000:8080
    environment:
      C9_WORKSPACE: '/var/www/html'
      C9_USER: 'username'
      C9_PASS: 'password'
    volumes:
      - ./workspace:/var/www/html
